version: '3.8'

services:
  protonvpn-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protonvpn-cli
    restart: unless-stopped
    # The application needs to run with elevated privileges to configure VPN
    privileged: true
    # Network capabilities needed for VPN functionality
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # Mount the host's /dev/net/tun device for VPN tunneling
    devices:
      - /dev/net/tun:/dev/net/tun
    # Mount configuration directory for persistent storage
    volumes:
      - protonvpn-config:/root/.pvpn-cli
    # Override the default command to keep the container running
    # You can exec into this container to run ProtonVPN commands
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  protonvpn-config:
    driver: local 